name = "rx_gleam"
version = "0.1.0"
description = "Serialized single-actor Reactive Extensions for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "ORESoftware", repo = "rx-gleam" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleeunit = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"

[dev-dependencies]
